language: node_js

node_js:
  - 0.10
  - 0.11

before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g typescript
  - npm install -g rollup
  - bower install

script:
  - gulp ci
